---

  - name: Start role
    debug:
      msg: "########### CONFIGURE GRAFANA ###########"

  - name: Copy dashboard json
    copy:
      src: node-exporter-full_rev27.json
      dest: "{{home_dir}}/node-exporter-full_rev27.json"

  - name: Wait for port 3000 is ready
    wait_for:
      port: 3000
      delay: 10

  - name: Get API key
    shell: "curl -X POST -H \"Content-Type: application/json\" -d '{\"name\":\"apikeycurl-{{ ansible_date_time.iso8601_basic }}\", \"role\": \"Admin\"}' http://admin:admin@localhost:3000/api/auth/keys"
    register: apikey

  - debug:
      var: (apikey.stdout | from_json).key

  - name: Add prometheus as datasource
    shell: "curl -X POST --insecure -H \"Authorization: Bearer {{(apikey.stdout | from_json).key}}\" -H \"Content-Type: application/json\" -d '{\"name\":\"prometheus\", \"type\":\"prometheus\", \"url\":\"http://localhost:9090\", \"access\":\"proxy\", \"basicAuth\":false}' http://admin:admin@localhost:3000/api/datasources"
    register: output

  - debug:
      var: output.stdout

  - name: Import dashboard to grafana
    shell: "curl -X POST --insecure -H \"Authorization: Bearer {{(apikey.stdout | from_json).key}}\" -H \"Content-Type: application/json\" -d @{{home_dir}}/node-exporter-full_rev27.json http://localhost:3000/api/dashboards/db"
    register: output

  - debug:
      var: output.stdout

